version: "3.7"
services:
    client:
        image: ndiklas/yolo-client:1.0
        build:  
            context: . 
            dockerfile: Client.Dockerfile
        ports:
            - 3000:3000
    backend:
        image: ndiklas/yolo-backend:1.0
        build:
            context: .
            dockerfile: Back.Dockerfile
        ports:
            - 5000:5000
        depends_on:
            - mongo
    mongo:
        image: mongo
        ports:
            - 27017:27017